version: '2'

services:
  checkmk:
    container_name: checkmk
    image: checkmk/check-mk-raw:2.0.0-latest
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/dockervolumes/checkmk/data:/omd/sites
      - /opt/dockervolumes/checkmk/backups:/backups
    ports:
      - 8181:5000
      - 162:162/udp
      - 514:514/udp
      - 514:514/tcp
    environment:
      - CMK_SITE_ID=cla