version: '3'

services:
  # VPN container
  # All containers force their network traffic through this container
  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun
    restart: always
    network_mode: bridge
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - FIREWALL_OUTBOUND_SUBNETS=10.10.4.0/24
      - FIREWALL_OUTBOUND_SUBNETS=10.10.3.0/24
      - FIREWALL_VPN_INPUT_PORTS=55676
      - VPNSP=mullvad
      - VPN_TYPE=wireguard
      - SERVER_CITIES=Zurich
      - WIREGUARD_PRIVATE_KEY=XXXX
      - WIREGUARD_ADDRESSES=XXXX
    volumes:
      - /opt/dockervolumes/gluetun:/gluetun
    labels:
      - com.centurylinklabs.watchtower.enable=false
    ports:
      # Host:Container/tcp|udp
      # If not specified it will be TCP
      # Sonarr
      - 8989:8989
      # Radarr
      - 7878:7878
      # Prowlarr
      - 9696:9696
      # qBittorrent
      - 8182:8080
      # Add more ports here as needed



  # Sonarr
  # For downloading TV shows
  # Runs on port 8989
  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr
    restart: always
    network_mode: service:gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /opt/dockervolumes/sonarr/config:/config
      - /mnt/storage/tv:/tv
      - /mnt/storage/downloads:/downloads
    labels:
      - com.centurylinklabs.watchtower.enable=false



  # Radarr
  # For downloading movies
  # Runs on port 7878
  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr
    restart: always
    network_mode: service:gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /opt/dockervolumes/radarr/config:/config
      - /mnt/storage/films:/movies
      - /mnt/storage/downloads:/downloads
    labels:
      - com.centurylinklabs.watchtower.enable=false



  # Prowlarr
  # Indexer for Sonarr and Radarr
  # Runs on port 9696
  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:develop
    restart: always
    network_mode: service:gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /opt/dockervolumes/prowlarr/config:/config
    labels:
      - com.centurylinklabs.watchtower.enable=false



  # qBittorrent
  # Torrent downloader
  # Runs on port 8080
  qbittorrent:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent
    restart: always
    network_mode: service:gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - WEBUI_PORT=8080
    volumes:
      - /opt/dockervolumes/qbittorrent/config:/config
      - /mnt/storage/downloads:/downloads
    labels:
      - com.centurylinklabs.watchtower.enable=false