version: '2'

services:
  # Filebrowser
  # For web management of files
  # Runs on port 81
  # To ensure the DB containing your login persists through a rebuild, run the below on the container host
  # mkdir /opt/dockervolumes/filebrowser/
  # touch /opt/dockervolumes/filebrowser/filebrowser.db
  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser
    restart: always
    volumes:
      - /opt/dockervolumes:/srv
      - /opt/dockervolumes/filebrowser/filebrowser.db:/database.db
    ports:
      - 81:80