version: '2'

services:
  jellyfin:
    container_name: jellyfin
    image: linuxserver/jellyfin
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /opt/dockervolumes/jellyfin/config:/config
      - /mnt/storage/tv:/data/tvshows
      - /mnt/storage/films:/data/movies
    ports:
      - 8096:8096