version: '2'

services:
  jellyfin:
    container_name: jellyfin
    image: lscr.io/linuxserver/jellyfin
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /opt/dockervolumes/jellyfin/config:/config
      - /mnt/storage/tv:/data/tvshows
      - /mnt/storage/films:/data/movies
      - /mnt/storage/transcodes:/transcodes
    ports:
      - 8096:8096
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellyfin.rule=Host(`jellyfin.domain.com`)
      - traefik.http.routers.jellyfin.entrypoints=websecure
      - traefik.http.routers.jellyfin.tls.certresolver=cloudflare
    networks:
      - proxy
networks:
  proxy:
    external: true