version: '2'

services:
  # PiHole
  # Runs on port 82
  # Ensure you disable DNS on the host (assuming Ubuntu) using the below commands
  # systemctl stop systemd-resolved
  # systemctl disable systemd-resolved
  # Access through http://IP/admin
  pihole:
    container_name: pihole
    image: pihole/pihole
    restart: always
    environment:
      TZ: Europe/London
    volumes:
      - /opt/dockervolumes/pihole/etc:/etc/pihole/
      - /opt/dockervolumes/pihole/dnsmasqd:/etc/dnsmasq.d/
    ports:
      - 10.10.3.1:53:53/tcp
      - 10.10.3.1:53:53/udp
      - 67:67/udp
      - 82:80/tcp
      - 444:443/tcp
    dns:
      - 127.0.0.1
      - 1.1.1.1
      - 1.0.0.1
      - 8.8.8.8
      - 8.8.4.4
    cap_add:
     - NET_ADMIN