providers:
  docker:
    exposedByDefault: false

log:
  level: DEBUG

api:
  dashboard: true

certificatesResolvers:
  cloudflare:
    acme:
      email: ${CLOUDFLARE_EMAIL}
      storage: /letsencrypt/acme.json
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 30
        disablePropagationCheck: true

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443
    http:
      tls:
        certResolver: cloudflare

serversTransport:
  insecureSkipVerify: true